<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement("INSERT INTO `setting_countries` (`id`, `name_en`, `name_zhHans`, `name_zhHant`, `name_vn`, `iso`) VALUES
(1, 'Afghanistan', '阿富汗', '阿富汗', 'Áp-ga-ni-xtan', 'AF'),
(2, 'Aland Islands', '奥兰群岛', '奧蘭群島', 'Quần đảo Åland', 'AX'),
(3, 'Albania', '阿尔巴尼亚', '阿爾巴尼亞', 'Albani', 'AL'),
(4, 'Algeria', '阿尔及利亚', '阿爾及利亞', 'An-giê-ri', 'DZ'),
(5, 'American Samoa', '美属萨摩亚', '美屬薩摩亞', 'Đảo Somoa thuộc Mỹ', 'AS'),
(6, 'Andorra', '安道尔', '安道爾', 'An-đô-ra', 'AD'),
(7, 'Angola', '安哥拉', '安哥拉', 'Ăng-gô-la', 'AO'),
(8, 'Anguilla', '安圭拉', '安圭拉', 'An-gu-đa', 'AI'),
(9, 'Antarctica', '南极洲', '南極洲', 'Châu Nam Cực', 'AQ'),
(10, 'Antigua and Barbuda', '安提瓜和巴布达', '安提瓜和巴布達', 'An-ti-ga và Ba-bu-đa', 'AG'),
(11, 'Argentina', '阿根廷', '阿根廷', 'Ác-hen-ti-na', 'AR'),
(12, 'Armenia', '亚美尼亚', '亞美尼亞', 'Ác-mê-ni', 'AM'),
(13, 'Aruba', '阿鲁巴', '阿魯巴', 'Aruba', 'AW'),
(14, 'Australia', '澳大利亚', '澳大利亞', 'Úc', 'AU'),
(15, 'Austria', '奥地利', '奧地利', 'Áo', 'AT'),
(16, 'Azerbaijan', '阿塞拜疆', '阿塞拜疆', 'Ai-déc-bai-gian', 'AZ'),
(17, 'Bahamas', '巴哈马', '巴哈馬', 'Ba-ha-ma', 'BS'),
(18, 'Bahrain', '巴林', '巴林', 'Ba-ranh', 'BH'),
(19, 'Bangladesh', '孟加拉国', '孟加拉國', 'Băng-la-đét', 'BD'),
(20, 'Barbados', '巴巴多斯', '巴巴多斯', 'Ba-ba-đốt', 'BB'),
(21, 'Belarus', '白俄罗斯', '白俄羅斯', 'Bê-la-rút', 'BY'),
(22, 'Belgium', '比利时', '比利時', 'Bỉ', 'BE'),
(23, 'Belize', '伯利兹', '伯利茲', 'Bê-li-xt', 'BZ'),
(24, 'Benin', '贝宁', '貝寧', 'Bê-nanh', 'BJ'),
(25, 'Bermuda', '百慕大', '百慕大', 'Bermuda', 'BM'),
(26, 'Bhutan', '不丹', '不丹', 'Bu-tan', 'BT'),
(27, 'Bolivia, Plurinational State of Bolivia', '玻利维亚', '玻利維亞', 'Bô-li-vi-a', 'BO'),
(28, 'Bonaira', '博内尔岛', '博內爾島', 'Bonaira', 'BV'),
(29, 'Bosnia and Herzegovina', '波斯尼亚和黑塞哥维那', '波斯尼亞和黑塞哥維那', 'Bô-xi-ni-a và Hắc-xai-gô-vi-na', 'BA'),
(30, 'Botswana', '博茨瓦纳', '博茨瓦納', 'Bốt-xoa-na', 'BW'),
(31, 'Bouvet Island', '布维岛', '布維島', 'Đảo Bouvet', 'BV'),
(32, 'Brazil', '巴西', '巴西', 'Bra-xin', 'BR'),
(33, 'British Indian Ocean Territory', '英属印度洋领地', '英屬印度洋領地', 'Lãnh thổ Ấn Độ Dương thuộc Anh', 'IO'),
(34, 'Brunei Darussalam', '文莱达鲁萨兰国', '文萊達魯薩蘭國', 'Bru-nây', 'BN'),
(35, 'Bulgaria', '保加利亚', '保加利亞', 'Bô-gi-a-ri', 'BG'),
(36, 'Burkina Faso', '布基纳法索', '布基納法索', 'Burkina Faso', 'BF'),
(37, 'Burundi', '布隆迪', '布隆迪', 'Bu-run-đi', 'BI'),
(38, 'Cambodia', '柬埔寨', '柬埔寨', 'Cam-pu-chia', 'KH'),
(39, 'Cameroon', '喀麦隆', '喀麥隆', 'Cam-ru-ni', 'CM'),
(40, 'Canada', '加拿大', '加拿大', 'Ca-na-đa', 'CA'),
(41, 'Cape Verde', '佛得角', '佛得角', 'Cape Verde', 'CV'),
(42, 'Cayman Islands', '开曼群岛', '開曼群島', 'Quần đảo Cayman', 'KY'),
(43, 'Central African Republic', '中非共和国', '中非共和國', 'Cộng hòa Trung Phi', 'CF'),
(44, 'Chad', '乍得', '乍得', 'Chad', 'TD'),
(45, 'Chile', '智利', '智利', 'Chi-lê', 'CL'),
(46, 'China', '中国', '中國', 'Trung Quốc', 'CN'),
(47, 'Christmas Island', '圣诞岛', '聖誕島', 'Đảo Giáng Sinh', 'CX'),
(48, 'Cocos (Keeling) Islands', '科科斯（基林）群岛', '科科斯（基林）群島', 'Quần đảo Cocos (Keeling)', 'CC'),
(49, 'Colombia', '哥伦比亚', '哥倫比亞', 'Colombia', 'CO'),
(50, 'Comoros', '科摩罗', '科摩羅', 'Cô-mô', 'KM'),
(51, 'Congo', '刚果', '剛果', 'Công-gô', 'CG'),
(52, 'Congo, Democratic Republic of the', '刚果民主共和国', '剛果民主共和國', 'Cộng hòa Dân chủ Công-gô', 'CD'),
(53, 'Cook Islands', '库克群岛', '庫克群島', 'Quần đảo Cook', 'CK'),
(54, 'Costa Rica', '哥斯达黎加', '哥斯達黎加', 'Cộng hòa Costa Rica', 'CR'),
(55, 'Croatia', '克罗地亚', '克羅地亞', 'Croatia', 'HR'),
(56, 'Cuba', '古巴', '古巴', 'Cu Ba', 'CU'),
(57, 'Cyprus', '塞浦路斯', '塞浦路斯', 'Síp', 'CY'),
(58, 'Czech Republic', '捷克共和国', '捷克共和國', 'Cộng hòa Séc', 'CZ'),
(59, 'Côte d\'Ivoire', '科特迪瓦', '科特迪瓦', 'Bờ Biển Ngà', 'CI'),
(60, 'Denmark', '丹麦', '丹麥', 'Đan Mạch', 'DK'),
(61, 'Djibouti', '吉布提', '吉布提', 'Djibouti', 'DJ'),
(62, 'Dominica', '多米尼克', '多米尼克', 'Dominica', 'DM'),
(63, 'Dominican Republic', '多米尼加共和国', '多米尼加共和國', 'Cộng hòa Dominica', 'DO'),
(64, 'Ecuador', '厄瓜多尔', '厄瓜多爾', 'Ecuador', 'EC'),
(65, 'Egypt', '埃及', '埃及', 'Ai Cập', 'EG'),
(66, 'El Salvador', '萨尔瓦多', '薩爾瓦多', 'El Salvador', 'SV'),
(67, 'Equatorial Guinea', '赤道几内亚', '赤道幾內亞', 'Ghi-nê Xích-đạo', 'GQ'),
(68, 'Eritrea', '厄立特里亚', '厄立特裡亞', 'Eritrea', 'ER'),
(69, 'Estonia', '爱沙尼亚', '愛沙尼亞', 'Estonia', 'EE'),
(70, 'Eswatini', '斯威士兰', '斯威士蘭', 'Eswatini', 'SZ'),
(71, 'Ethiopia', '埃塞俄比亚', '埃塞俄比亞', 'Ê-ti-ô-pi-a', 'ET'),
(72, 'Falkland Islands (Malvinas)', '福克兰群岛（马尔维纳斯）', '福克蘭群島（馬爾維納斯）', 'Quần đảo Falkland (Malvinas)', 'FK'),
(73, 'Faroe Islands', '法罗群岛', '法羅群島', 'Quần đảo Faroe', 'FO'),
(74, 'Fiji', '斐济', '斐濟', 'Phi-gi', 'FJ'),
(75, 'Finland', '芬兰', '芬蘭', 'Phần Lan', 'FI'),
(76, 'France', '法国', '法國', 'Pháp', 'FR'),
(77, 'French Guiana', '法属圭亚那', '法屬圭亞那', 'Quiana thuộc Pháp', 'GF'),
(78, 'French Polynesia', '法属波利尼西亚', '法屬波利尼西亞', 'Polynésie thuộc Pháp', 'PF'),
(79, 'French Southern Territories', '法属南部领地', '法屬南部領地', 'Lãnh thổ phía Nam của Pháp', 'TF'),
(80, 'Gabon', '加蓬', '加蓬', 'Gabon', 'GA'),
(81, 'Gambia', '冈比亚', '岡比亞', 'Gambia', 'GM'),
(82, 'Georgia', '格鲁吉亚', '格魯吉亞', 'Gruzia', 'GE'),
(83, 'Germany', '德国', '德國', 'Đức', 'DE'),
(84, 'Ghana', '加纳', '加納', 'Ghana', 'GH'),
(85, 'Gibraltar', '直布罗陀', '直布羅陀', 'Gibraltar', 'GI'),
(86, 'Greece', '希腊', '希臘', 'Hy Lạp', 'GR'),
(87, 'Greenland', '格陵兰', '格陵蘭', 'Greenland', 'GL'),
(88, 'Grenada', '格林纳达', '格林納達', 'Grenada', 'GD'),
(89, 'Guadeloupe', '瓜德罗普', '瓜德羅普', 'Guadeloupe', 'GP'),
(90, 'Guam', '关岛', '關島', 'Guam', 'GU'),
(91, 'Guatemala', '危地马拉', '危地馬拉', 'Guatemala', 'GT'),
(92, 'Guernsey', '根西岛', '根西島', 'Guernsey', 'GG'),
(93, 'Guinea', '几内亚', '幾內亞', 'Guinê', 'GN'),
(94, 'Guinea-Bissau', '几内亚比绍', '幾內亞比紹', 'Guinê-Bissau', 'GW'),
(95, 'Guyana', '圭亚那', '圭亞那', 'Guyana', 'GY'),
(96, 'Haiti', '海地', '海地', 'Haiti', 'HT'),
(97, 'Heard Island and McDonald Islands', '赫德岛和麦克唐纳群岛', '赫德島和麥克唐納群島', 'Đảo Heard và Quần đảo McDonald', 'HM'),
(98, 'Holy See', '梵蒂冈', '梵蒂岡', 'Thánh Điện Vatican', 'VA'),
(99, 'Honduras', '洪都拉斯', '洪都拉斯', 'Honduras', 'HN'),
(100, 'Hong Kong', '香港', '香港', 'Hồng Kông', 'HK'),
(101, 'Hungary', '匈牙利', '匈牙利', 'Hungary', 'HU'),
(102, 'Iceland', '冰岛', '冰島', 'Iceland', 'IS'),
(103, 'India', '印度', '印度', 'Ấn Độ', 'IN'),
(104, 'Indonesia', '印度尼西亚', '印度尼西亞', 'Indonesia', 'ID'),
(105, 'Iran (Islamic Republic of)', '伊朗', '伊朗', 'Iran', 'IR'),
(106, 'Iraq', '伊拉克', '伊拉克', 'Iraq', 'IQ'),
(107, 'Ireland', '爱尔兰', '愛爾蘭', 'Ai-len', 'IE'),
(108, 'Isle of Man', '马恩岛', '馬恩島', 'Đảo Man', 'IM'),
(109, 'Israel', '以色列', '以色列', 'Israel', 'IL'),
(110, 'Italy', '意大利', '意大利', 'Ý', 'IT'),
(111, 'Jamaica', '牙买加', '牙買加', 'Jamaica', 'JM'),
(112, 'Japan', '日本', '日本', 'Nhật Bản', 'JP'),
(113, 'Jersey', '泽西岛', '澤西島', 'Jersey', 'JE'),
(114, 'Jordan', '约旦', '約旦', 'Jordan', 'JO'),
(115, 'Kazakhstan', '哈萨克斯坦', '哈薩克斯坦', 'Kazakhstan', 'KZ'),
(116, 'Kenya', '肯尼亚', '肯尼亞', 'Kenya', 'KE'),
(117, 'Kiribati', '基里巴斯', '基里巴斯', 'Kiribati', 'KI'),
(118, 'Korea (Democratic People\'s Republic of)', '朝鲜', '朝鮮', 'Triều Tiên', 'KP'),
(119, 'Korea (Republic of)', '韩国', '韓國', 'Hàn Quốc', 'KR'),
(120, 'Kuwait', '科威特', '科威特', 'Kuwait', 'KW'),
(121, 'Kyrgyzstan', '吉尔吉斯斯坦', '吉爾吉斯斯坦', 'Kyrgyzstan', 'KG'),
(122, 'Lao People\'s Democratic Republic', '老挝', '老撾', 'Lào', 'LA'),
(123, 'Latvia', '拉脱维亚', '拉脫維亞', 'Latvia', 'LV'),
(124, 'Lebanon', '黎巴嫩', '黎巴嫩', 'Lebanon', 'LB'),
(125, 'Lesotho', '莱索托', '萊索托', 'Lesotho', 'LS'),
(126, 'Liberia', '利比里亚', '利比裡亞', 'Liberia', 'LR'),
(127, 'Libya', '利比亚', '利比亞', 'Libya', 'LY'),
(128, 'Liechtenstein', '列支敦士登', '列支敦士登', 'Liechtenstein', 'LI'),
(129, 'Lithuania', '立陶宛', '立陶宛', 'Lithuania', 'LT'),
(130, 'Luxembourg', '卢森堡', '盧森堡', 'Luxembourg', 'LU'),
(131, 'Macao', '澳门', '澳門', 'Macao', 'MO'),
(132, 'North Macedonia', '北马其顿', '北馬其頓', 'Bắc Macedonia', 'MK'),
(133, 'Madagascar', '马达加斯加', '馬達加斯加', 'Madagascar', 'MG'),
(134, 'Malawi', '马拉维', '馬拉維', 'Malawi', 'MW'),
(135, 'Malaysia', '马来西亚', '馬來西亞', 'Malaysia', 'MY'),
(136, 'Maldives', '马尔代夫', '馬爾代夫', 'Maldives', 'MV'),
(137, 'Mali', '马里', '馬里', 'Mali', 'ML'),
(138, 'Malta', '马耳他', '馬耳他', 'Malta', 'MT'),
(139, 'Marshall Islands', '马绍尔群岛', '馬紹爾群島', 'Quần đảo Marshall', 'MH'),
(140, 'Martinique', '马提尼克', '馬提尼克', 'Martinique', 'MQ'),
(141, 'Mauritania', '毛里塔尼亚', '毛里塔尼亞', 'Mauritania', 'MR'),
(142, 'Mauritius', '毛里求斯', '毛里求斯', 'Mauritius', 'MU'),
(143, 'Mayotte', '马约特', '馬約特', 'Mayotte', 'YT'),
(144, 'Mexico', '墨西哥', '墨西哥', 'Mexico', 'MX'),
(145, 'Micronesia (Federated States of)', '密克罗尼西亚', '密克羅尼西亞', 'Micronesia', 'FM'),
(146, 'Moldova (Republic of)', '摩尔多瓦', '摩爾多瓦', 'Moldova', 'MD'),
(147, 'Monaco', '摩纳哥', '摩納哥', 'Monaco', 'MC'),
(148, 'Mongolia', '蒙古', '蒙古', 'Mông Cổ', 'MN'),
(149, 'Montenegro', '黑山', '黑山', 'Montenegro', 'ME'),
(150, 'Montserrat', '蒙塞拉特', '蒙塞拉特', 'Montserrat', 'MS'),
(151, 'Morocco', '摩洛哥', '摩洛哥', 'Morocco', 'MA'),
(152, 'Mozambique', '莫桑比克', '莫桑比克', 'Mozambique', 'MZ'),
(153, 'Myanmar', '缅甸', '緬甸', 'Myanmar', 'MM'),
(154, 'Namibia', '纳米比亚', '納米比亞', 'Namibia', 'NA'),
(155, 'Nauru', '瑙鲁', '瑙魯', 'Nauru', 'NR'),
(156, 'Nepal', '尼泊尔', '尼泊爾', 'Nepal', 'NP'),
(157, 'Netherlands', '荷兰', '荷蘭', 'Hà Lan', 'NL'),
(158, 'New Caledonia', '新喀里多尼亚', '新喀裡多尼亞', 'New Caledonia', 'NC'),
(159, 'New Zealand', '新西兰', '新西蘭', 'New Zealand', 'NZ'),
(160, 'Nicaragua', '尼加拉瓜', '尼加拉瓜', 'Nicaragua', 'NI'),
(161, 'Niger', '尼日尔', '尼日爾', 'Niger', 'NE'),
(162, 'Nigeria', '尼日利亚', '尼日利亞', 'Nigeria', 'NG'),
(163, 'Niue', '纽埃', '紐埃', 'Niue', 'NU'),
(164, 'Norfolk Island', '诺福克岛', '諾福克島', 'Đảo Norfolk', 'NF'),
(165, 'North Korea', '北朝鲜', '北朝鮮', 'Bắc Triều Tiên', 'KP'),
(166, 'Northern Mariana Islands', '北马里亚纳群岛', '北馬里亞納群島', 'Quần đảo Bắc Mariana', 'MP'),
(167, 'Norway', '挪威', '挪威', 'Na Uy', 'NO'),
(168, 'Oman', '阿曼', '阿曼', 'Oman', 'OM'),
(169, 'Pakistan', '巴基斯坦', '巴基斯坦', 'Pakistan', 'PK'),
(170, 'Palau', '帕劳', '帛琉', 'Palau', 'PW'),
(171, 'Palestine, State of', '巴勒斯坦', '巴勒斯坦', 'Palestine', 'PS'),
(172, 'Panama', '巴拿马', '巴拿馬', 'Panama', 'PA'),
(173, 'Papua New Guinea', '巴布亚新几内亚', '巴布亞新幾內亞', 'Papua New Guinea', 'PG'),
(174, 'Paraguay', '巴拉圭', '巴拉圭', 'Paraguay', 'PY'),
(175, 'Peru', '秘鲁', '秘魯', 'Peru', 'PE'),
(176, 'Philippines', '菲律宾', '菲律賓', 'Philippines', 'PH'),
(177, 'Pitcairn', '皮特凯恩', '皮特凱恩', 'Pitcairn', 'PN'),
(178, 'Poland', '波兰', '波蘭', 'Ba Lan', 'PL'),
(179, 'Portugal', '葡萄牙', '葡萄牙', 'Bồ Đào Nha', 'PT'),
(180, 'Puerto Rico', '波多黎各', '波多黎各', 'Puerto Rico', 'PR'),
(181, 'Qatar', '卡塔尔', '卡塔爾', 'Qatar', 'QA'),
(182, 'Réunion', '留尼汪', '留尼汪', 'Réunion', 'RE'),
(183, 'Romania', '罗马尼亚', '羅馬尼亞', 'Romania', 'RO'),
(184, 'Russia', '俄罗斯', '俄羅斯', 'Nga', 'RU'),
(185, 'Rwanda', '卢旺达', '盧旺達', 'Rwanda', 'RW'),
(186, 'Saint Barthélemy', '圣巴泰勒米', '聖巴泰勒米', 'Saint Barthélemy', 'BL'),
(187, 'Saint Helena, Ascension and Tristan da Cunha', '圣赫勒拿、阿森松与特里斯坦-达库尼亚', '聖赫勒拿、阿森松與特里斯坦-達庫尼亞', 'Saint Helena', 'SH'),
(188, 'Saint Kitts and Nevis', '圣基茨和尼维斯', '聖基茨和尼維斯', 'Saint Kitts và Nevis', 'KN'),
(189, 'Saint Lucia', '圣卢西亚', '聖盧西亞', 'Saint Lucia', 'LC'),
(190, 'Saint Martin (French part)', '法属圣马丁', '法屬聖馬丁', 'Saint-Martin', 'MF'),
(191, 'Saint Pierre and Miquelon', '圣皮埃尔和密克隆', '聖皮埃爾和密克隆', 'Saint Pierre và Miquelon', 'PM'),
(192, 'Saint Vincent and the Grenadines', '圣文森特和格林纳丁斯', '聖文森特和格林納丁斯', 'Saint Vincent và Grenadines', 'VC'),
(193, 'Samoa', '萨摩亚', '薩摩亞', 'Samoa', 'WS'),
(194, 'San Marino', '圣马力诺', '聖馬力諾', 'San Marino', 'SM'),
(195, 'Sao Tome and Principe', '圣多美和普林西比', '聖多美和普林西比', 'São Tomé và Príncipe', 'ST'),
(196, 'Saudi Arabia', '沙特阿拉伯', '沙特阿拉伯', 'Ả Rập Saudi', 'SA'),
(197, 'Senegal', '塞内加尔', '塞內加爾', 'Senegal', 'SN'),
(198, 'Serbia', '塞尔维亚', '塞爾維亞', 'Serbia', 'RS'),
(199, 'Seychelles', '塞舌尔', '塞舌爾', 'Seychelles', 'SC'),
(200, 'Sierra Leone', '塞拉利昂', '塞拉利昂', 'Sierra Leone', 'SL'),
(201, 'Singapore', '新加坡', '新加坡', 'Singapore', 'SG'),
(202, 'Sint Maarten (Dutch part)', '荷属圣马丁', '荷屬聖馬丁', 'Sint Maarten', 'SX'),
(203, 'Slovakia', '斯洛伐克', '斯洛伐克', 'Slovakia', 'SK'),
(204, 'Slovenia', '斯洛文尼亚', '斯洛文尼亞', 'Slovenia', 'SI'),
(205, 'Solomon Islands', '所罗门群岛', '所羅門群島', 'Quần đảo Solomon', 'SB'),
(206, 'Somalia', '索马里', '索馬里', 'Somalia', 'SO'),
(207, 'South Africa', '南非', '南非', 'Nam Phi', 'ZA'),
(208, 'South Georgia and the South Sandwich Islands', '南乔治亚岛和南桑威奇群岛', '南喬治亞島和南桑威奇群島', 'Quần đảo Nam Georgia và Nam Sandwich', 'GS'),
(209, 'South Korea', '韩国', '韓國', 'Hàn Quốc', 'KR'),
(210, 'South Sudan', '南苏丹', '南蘇丹', 'Nam Sudan', 'SS'),
(211, 'Spain', '西班牙', '西班牙', 'Tây Ban Nha', 'ES'),
(212, 'Sri Lanka', '斯里兰卡', '斯里蘭卡', 'Sri Lanka', 'LK'),
(213, 'Sudan', '苏丹', '蘇丹', 'Sudan', 'SD'),
(214, 'Suriname', '苏里南', '蘇里南', 'Suriname', 'SR'),
(215, 'Svalbard and Jan Mayen', '斯瓦尔巴特和扬马延', '斯瓦爾巴特和揚馬延', 'Svalbard và Jan Mayen', 'SJ'),
(216, 'Sweden', '瑞典', '瑞典', 'Thụy Điển', 'SE'),
(217, 'Switzerland', '瑞士', '瑞士', 'Thụy Sĩ', 'CH'),
(218, 'Syria', '叙利亚', '敘利亞', 'Syria', 'SY'),
(219, 'Taiwan', '台湾', '台灣', 'Đài Loan', 'TW'),
(220, 'Tajikistan', '塔吉克斯坦', '塔吉克斯坦', 'Tajikistan', 'TJ'),
(221, 'Tanzania', '坦桑尼亚', '坦桑尼亞', 'Tanzania', 'TZ'),
(222, 'Thailand', '泰国', '泰國', 'Thái Lan', 'TH'),
(223, 'Timor-Leste', '东帝汶', '東帝汶', 'Timor-Leste', 'TL'),
(224, 'Togo', '多哥', '多哥', 'Togo', 'TG'),
(225, 'Tokelau', '托克劳', '托克勞', 'Tokelau', 'TK'),
(226, 'Tonga', '汤加', '湯加', 'Tonga', 'TO'),
(227, 'Trinidad and Tobago', '特立尼达和多巴哥', '特立尼達和多巴哥', 'Trinidad và Tobago', 'TT'),
(228, 'Tunisia', '突尼斯', '突尼斯', 'Tunisia', 'TN'),
(229, 'Turkey', '土耳其', '土耳其', 'Thổ Nhĩ Kỳ', 'TR'),
(230, 'Turkmenistan', '土库曼斯坦', '土庫曼斯坦', 'Turkmenistan', 'TM'),
(231, 'Turks and Caicos Islands', '特克斯和凯科斯群岛', '特克斯和凱科斯群島', 'Quần đảo Turks và Caicos', 'TC'),
(232, 'Tuvalu', '图瓦卢', '圖瓦盧', 'Tuvalu', 'TV'),
(233, 'U.S. Virgin Islands', '美属维尔京群岛', '美屬維爾京群島', 'Quần đảo Virgin thuộc Mỹ', 'VI'),
(234, 'Uganda', '乌干达', '烏干達', 'Uganda', 'UG'),
(235, 'Ukraine', '乌克兰', '烏克蘭', 'Ukraine', 'UA'),
(236, 'United Arab Emirates', '阿拉伯联合酋长国', '阿拉伯聯合酋長國', 'Các Tiểu vương quốc Ả Rập Thống nhất', 'AE'),
(237, 'United Kingdom', '英国', '英國', 'Vương quốc Liên hiệp Anh và Bắc Ireland', 'GB'),
(238, 'United States', '美国', '美國', 'Hoa Kỳ', 'US'),
(239, 'Uruguay', '乌拉圭', '烏拉圭', 'Uruguay', 'UY'),
(240, 'Uzbekistan', '乌兹别克斯坦', '烏茲別克斯坦', 'Uzbekistan', 'UZ'),
(241, 'Vanuatu', '瓦努阿图', '瓦努阿圖', 'Vanuatu', 'VU'),
(242, 'Vatican', '梵蒂冈', '梵蒂岡', 'Vatican', 'VA'),
(243, 'Venezuela', '委内瑞拉', '委內瑞拉', 'Venezuela', 'VE'),
(244, 'Vietnam', '越南', '越南', 'Việt Nam', 'VN'),
(245, 'Wallis and Futuna', '瓦利斯和富图纳', '瓦利斯和富圖納', 'Wallis và Futuna', 'WF'),
(246, 'Western Sahara', '西撒哈拉', '西撒哈拉', 'Tây Sahara', 'EH'),
(247, 'Yemen', '也门', '也門', 'Yemen', 'YE'),
(248, 'Zambia', '赞比亚', '贊比亞', 'Zambia', 'ZM'),
(249, 'Zimbabwe', '津巴布韦', '津巴布韋', 'Zimbabwe', 'ZW');
        ");
    }
}
